const { contextBridge, ipcRenderer } = require('electron');

// Live push events from the server socket (relayed via main.js's socket.io
// connection, see connectRealtime()). Returns an unsubscribe function.
function subscribe(channel, callback) {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('api', {
  setTitleBarColor: (color, symbolColor) => ipcRenderer.invoke('window:setTitleBarColor', { color, symbolColor }),
  getAll: () => ipcRenderer.invoke('items:getAll'),
  saveItem: (item) => ipcRenderer.invoke('items:save', item),
  deleteItem: (id) => ipcRenderer.invoke('items:delete', id),
  addCategory: (category) => ipcRenderer.invoke('categories:add', category),
  renameCategory: (oldName, newName) => ipcRenderer.invoke('categories:rename', { oldName, newName }),
  deleteCategory: (category) => ipcRenderer.invoke('categories:delete', category),
  setCategoryImage: (name, fileName) => ipcRenderer.invoke('categories:setImage', { name, fileName }),
  setCategoryFields: (name, fields) => ipcRenderer.invoke('categories:setFields', { name, fields }),
  setCategoryTarget: (name, target) => ipcRenderer.invoke('categories:setTarget', { name, target }),
  setCategoryCaseDesign: (name, caseDesign) => ipcRenderer.invoke('categories:setCaseDesign', { name, caseDesign }),
  setCategoryOrder: (order) => ipcRenderer.invoke('categories:setOrder', order),
  submitToCatalog: (payload) => ipcRenderer.invoke('catalog:submit', payload),
  proposeCatalogPhoto: (payload) => ipcRenderer.invoke('catalog:proposePhoto', payload),
  proposeCatalogCategory: (name) => ipcRenderer.invoke('catalog:proposeCategory', name),
  pickImage: () => ipcRenderer.invoke('image:pick'),
  getImagePath: (fileName) => ipcRenderer.invoke('image:getPath', fileName),
  sendFeedback: (payload) => ipcRenderer.invoke('feedback:send', payload),
  reportCatalogEntry: (payload) => ipcRenderer.invoke('catalog:report', payload),
  exportZip: () => ipcRenderer.invoke('data:exportZip'),
  importZip: () => ipcRenderer.invoke('data:importZip'),
  exportCsv: () => ipcRenderer.invoke('data:exportCsv'),
  importCsv: () => ipcRenderer.invoke('data:importCsv'),
  exportPdf: (options) => ipcRenderer.invoke('data:exportPdf', options),
  pickImportSpreadsheet: () => ipcRenderer.invoke('data:pickImportSpreadsheet'),
  register: (payload) => ipcRenderer.invoke('auth:register', payload),
  login: (payload) => ipcRenderer.invoke('auth:login', payload),
  logout: () => ipcRenderer.invoke('auth:logout'),
  getSession: () => ipcRenderer.invoke('auth:getSession'),
  friendsList: () => ipcRenderer.invoke('friends:list'),
  friendsSendRequest: (toEmail) => ipcRenderer.invoke('friends:sendRequest', toEmail),
  friendsAcceptRequest: (id) => ipcRenderer.invoke('friends:acceptRequest', id),
  friendsDeclineRequest: (id) => ipcRenderer.invoke('friends:declineRequest', id),
  blocksList: () => ipcRenderer.invoke('blocks:list'),
  blockUser: (userId) => ipcRenderer.invoke('blocks:block', userId),
  unblockUser: (userId) => ipcRenderer.invoke('blocks:unblock', userId),
  groupsList: () => ipcRenderer.invoke('groups:list'),
  groupsDiscover: () => ipcRenderer.invoke('groups:discover'),
  groupsCreate: (payload) => ipcRenderer.invoke('groups:create', payload),
  groupsGet: (id) => ipcRenderer.invoke('groups:get', id),
  groupsJoin: (id) => ipcRenderer.invoke('groups:join', id),
  groupsAddMember: (id, username) => ipcRenderer.invoke('groups:addMember', { id, username }),
  groupsSetRole: (id, userId, role) => ipcRenderer.invoke('groups:setRole', { id, userId, role }),
  groupsKick: (id, userId) => ipcRenderer.invoke('groups:kick', { id, userId }),
  groupsBan: (id, userId) => ipcRenderer.invoke('groups:ban', { id, userId }),
  groupsDelete: (id) => ipcRenderer.invoke('groups:delete', id),
  conversationsList: () => ipcRenderer.invoke('conversations:list'),
  conversationsOpenDirect: (friendId) => ipcRenderer.invoke('conversations:openDirect', friendId),
  conversationsHistory: (id, before) => ipcRenderer.invoke('conversations:history', { id, before }),
  conversationsSend: (id, body) => ipcRenderer.invoke('conversations:send', { id, body }),
  conversationsMarkRead: (id) => ipcRenderer.invoke('conversations:markRead', id),
  notificationsList: () => ipcRenderer.invoke('notifications:list'),
  notificationsMarkRead: (id) => ipcRenderer.invoke('notifications:markRead', id),
  notificationsMarkAllRead: () => ipcRenderer.invoke('notifications:markAllRead'),
  onNewMessage: (cb) => subscribe('rt:message', cb),
  onNewNotification: (cb) => subscribe('rt:notification', cb),
  onTyping: (cb) => subscribe('rt:typing', cb),
  wishlistList: () => ipcRenderer.invoke('wishlist:list'),
  wishlistAdd: (payload) => ipcRenderer.invoke('wishlist:add', payload),
  wishlistUpdate: (payload) => ipcRenderer.invoke('wishlist:update', payload),
  wishlistRemove: (id) => ipcRenderer.invoke('wishlist:remove', id),
  forumListThreads: (category) => ipcRenderer.invoke('forum:listThreads', category),
  forumCreateThread: (payload) => ipcRenderer.invoke('forum:createThread', payload),
  forumGetThread: (threadId) => ipcRenderer.invoke('forum:getThread', threadId),
  forumReply: (threadId, body, level) => ipcRenderer.invoke('forum:reply', { threadId, body, level }),
  forumCloseThread: (threadId) => ipcRenderer.invoke('forum:closeThread', threadId),
  forumDeleteThread: (threadId) => ipcRenderer.invoke('forum:deleteThread', threadId),
  forumDeletePost: (postId) => ipcRenderer.invoke('forum:deletePost', postId),
  forumLikePost: (postId) => ipcRenderer.invoke('forum:likePost', postId),
  forumTrending: () => ipcRenderer.invoke('forum:trending'),
  forumLeaderboard: () => ipcRenderer.invoke('forum:leaderboard'),
  forumActiveCollectors: () => ipcRenderer.invoke('forum:activeCollectors'),
  forumActivity: () => ipcRenderer.invoke('forum:activity')
});
